# Generated by Django 6.0.3 on 2026-03-30 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('problem_summary', models.TextField()),
                ('solution_summary', models.TextField()),
                ('target_industry', models.CharField(max_length=100)),
                ('target_role', models.CharField(max_length=100)),
                ('target_company_size', models.CharField(max_length=50)),
                ('target_market', models.CharField(blank=True, max_length=100)),
                ('validation_goal_type', models.CharField(max_length=50)),
                ('validation_goal_count', models.PositiveIntegerField(default=1)),
                ('pilot_offer_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('live', 'Live'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntroRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_requests', to='campaign.campaign')),
                ('sme_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('campaign', 'sme_user')},
            },
        ),
        migrations.CreateModel(
            name='CampaignEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery_call_scheduled', models.BooleanField(default=False)),
                ('discovery_call_completed', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('pilot_discussion', 'Pilot Discussion'), ('letter_of_intent', 'Letter of Intent'), ('deposit_received', 'Deposit Received'), ('follow_up', 'Follow Up'), ('not_a_fit', 'Not a Fit'), ('no_decision', 'No Decision')], max_length=30)),
                ('founder_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intro_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='campaign.introrequest')),
            ],
        ),
    ]
