# Generated by Django 6.0.3 on 2026-04-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target_company_size',
            field=models.CharField(choices=[('1_10', '1–10 employees'), ('10_25', '10–25 employees'), ('25_100', '25–100 employees'), ('100_250', '100–250 employees'), ('250_plus', '250+ employees')], max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_industry',
            field=models.CharField(choices=[('logistics', 'Logistics'), ('transport', 'Transport'), ('construction', 'Construction'), ('field_service', 'Field Service'), ('manufacturing', 'Manufacturing'), ('finance', 'Finance'), ('hr', 'HR'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_role',
            field=models.CharField(choices=[('operations_manager', 'Operations Manager'), ('fleet_manager', 'Fleet Manager'), ('finance_manager', 'Finance Manager'), ('ceo', 'CEO / Founder'), ('it_manager', 'IT Manager'), ('hr_manager', 'HR Manager'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='validation_goal_type',
            field=models.CharField(choices=[('discovery_calls', 'Discovery Calls'), ('pilot_discussions', 'Pilot Discussions'), ('letters_of_intent', 'Letters of Intent'), ('deposits', 'Deposits'), ('waitlist_signups', 'Waitlist Signups')], max_length=50),
        ),
    ]
