# Generated by Django 6.0.3 on 2026-04-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_target_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_visual',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_visuals/'),
        ),
    ]
