# Generated by Django 6.0.3 on 2026-04-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_campaign_visual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_visual',
            new_name='campaign_image',
        ),
    ]
