# Generated by Django 6.0.3 on 2026-04-10 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_rename_campaign_visual_campaign_campaign_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('personal_message', models.TextField(blank=True)),
                ('invite_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('signed_up', 'Signed Up'), ('requested_intro', 'Requested Intro'), ('bounced', 'Bounced')], default='sent', max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='campaign.campaign')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_campaign_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
